<?php
/**
 * @file
 * Custom module for miscellaneous features on avidainc.com
 */

/**
 * Implements hook_init()
 */
function avida_site_init() {
  /*$data = 'http://fonts.googleapis.com/css?family=Chivo:400,400italic,900';
  $options = array(
    'type' => 'external',
  );
  
  drupal_add_css($data, $options);*/
}

/**
 * Implements hook_date_formatter_dates_alter().
 */
function avida_site_date_formatter_dates_alter(&$dates, $context) {
  $format_type = !empty($context['display']['settings']['format_type']) ? $context['display']['settings']['format_type'] : '';
  if ($format_type != 'event_teaser') return;
  
  foreach ($dates as &$value) {
    $formatted_array = explode(' ', $value['formatted']);
    $value['formatted'] = $formatted_array[0] . ' <strong>' . $formatted_array[1] . '</strong>';
  }
}
